version: '3.8'
services:
  app:
    container_name: python_prediction_room_temperature_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
    tty: true
